version: '3.1'

services:

  db:
    build: .
    image: mysql:8.0
    container_name: mysql_ringo
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: schema
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - 3307:3306
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
      - $PWD/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mysql-volume: