version: '3.8'

services:

  db:
    build: .
    container_name: mysql_ringo
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - 3307:3306
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
volumes:
  mysql-volume:
