executors:
  j11: 
    docker:
      - image: cimg/openjdk:11.0
orbs:
  maven: circleci/maven@1.2.0
  slack: circleci/slack@4.1
version: 2.1

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
          [
  {
    "type": "header",
    "text": {
      "type": "plain_text",
      "text": "New request"
    }
  },
  {
    "type": "section",
    "fields": [
      {
        "type": "mrkdwn",
        "text": "*Type:*\nPaid Time Off"
      },
      {
        "type": "mrkdwn",
        "text": "*Created by:*\n<example.com|Fred Enriquez>"
      }
    ]
  },
  {
    "type": "section",
    "fields": [
      {
        "type": "mrkdwn",
        "text": "*When:*\nAug 10 - Aug 13"
      }
    ]
  },
  {
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": "<https://example.com|View request>"
    }
  }
]

            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*ああああああああ*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j11

  send-notification:
    jobs:
      - notify:

          context: slack-circlecl-ringo
