executors:
  j11: 
    docker:
      - image: cimg/openjdk:11.0
orbs:
  maven: circleci/maven@1.2.0
  slack: circleci/slack@4.1
version: 2.1

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*ああああああああ*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j11

  send-notification:
    jobs:
      - notify:

          context: slack-circlecl-ringo

