executors:
  j11: 
    docker:
      - image: cimg/openjdk:11.0
orbs:
  maven: circleci/maven@1.2.0
  slack: circleci/slack@4.1
version: 2.1

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
            template: basic_fail_1
              - slack/notify:
                  event: pass
                  template: success_tagged_deploy_1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j11

  send-notification:
    jobs:
      - notify:

          context: slack-circlecl-ringo
